# This is a basic workflow to help you get started with Actions

name: CD-docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
        - ci-cd
        - Development
        - MergeReposBranch
    path: [ FrontEnd/** ]
  pull_request:
    branches: [ main, Development ]
    path: [ FrontEnd/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: 'FrontEnd'
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taxmodelfrontend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
