name: .NET

on:
  push:
    branches: [ main, Development, MergeReposBranch ]
    path: ["BackEnd/**"]
  pull_request:
    branches: [ main, Development ]
    path: ["BackEnd/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore **/TaskService/
    - name: Build
      run: dotnet build **/TaskService/back-end.csproj --no-restore
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: 'BackEnd/TaskService'
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/taxmodelbackend:latest
